### ISSUE TITLE
CFC: Publish a WG note

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/permissions-automation#3]
Hi @w3c/webappsec chairs, team, could you kindly start a CFC to publish this document as a FPWG-Note?:

https://w3c.github.io/permissions-automation/

This API was part of the Permissions API, but not exposed publicly by browsers... it's used by WPT tho, and it's quite helpful in that regard. 

I'll like to publish it as a FPWD Note, and for us to maintain it as a "non-normative living standard" (i.e., as a Note).

**Comment by annevk** [comment]
Shouldn't this be folded into the main Permissions specification? We ought to maintain WebDriver extensions as they contain normative implementation requirements, albeit not web-exposed ones.

**Comment by jyasskin** [comment]
According to https://github.com/w3c/permissions/issues/258, Marcos pulled it out because it doesn't have multiple implementations.

**Comment by marcoscaceres** [comment]
I don’t mind making this a normative spec, but still prefer keeping them separate.

**Comment by annevk** [comment]
I'd like to understand why. At least in my mind this kind of thing benefits from being maintained alongside the API and model. As you make changes to the API and model, you'll want to adjust this as well.

I also think that's what the WebDriver folks recommend. @jgraham maybe you can weigh in or ask the relevant person to do so?

**Comment by marcoscaceres** [comment]
I’ll check if the webkit folks are planning to implement it (they are implementing the permissions api literally as we speak). That might give us a second implementation.

Gecko supports updating permissions via mochitests, I believe… so maybe there is a way of implementing a web driver extension by reusing that? If anyone can point me to an example in Gecko of a web driver extension, I can evaluate how long it would take and maybe implement it.

**Comment by jgraham** [comment]
Yes, I think the common pattern is to keep the test API in the same document as the spec, to maximise the chance they stay in sync.

Re: gecko, there's an extremely incomplete (basically stub) implementation of `set permission` in marionette already c.f. https://searchfox.org/mozilla-central/source/remote/marionette/driver.js#2932 and https://searchfox.org/mozilla-central/source/remote/marionette/permissions.js#37. So basically all that's needed is to fill that out with whatever's required to actually make the backend work in more cases; that should just be the same as whatever mochitest does. That will make wpt work; if we also want geckodriver to work we need to add in the relevant HTTP frontend (but that's ~trivial).

**Comment by marcoscaceres** [comment]
Ok, I sent a PR putting it back into the original spec:
https://github.com/w3c/webdriver/pull/1639

I'm going to move the issues from here back to the other repo and remove this repo, as nothing was ever published from it.
